###
1. Creation of Numpy Arrays
2. Accessing Numpy array index
3. Basic Numpy Operations

### 1. Creation of Numpy Arrays

In [3]:
import numpy as np

In [5]:
# Creating rank 1 array
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [23]:
# Creating rank 2 array
arr2 =np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [13]:
# Creating array with tuple
arr3 = np.array((1,2,3,4,5,6))
print(arr3)

[1 2 3 4 5 6]


### 2. Accessing of Numpy Array Index

In [29]:
# Slicing
# Printing a range of array
sliced_arr = arr2[:2, ::2]
print(sliced_arr)

[[1 3]
 [4 6]]


In [37]:
# Printing elements at specific indexes
Indexed_arr = arr2[1,2]
print(Indexed_arr)

6
